name: Tests
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.6"
        toxenv:
          - "pep8"
          - "black"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install tox
      - run: tox -e ${{ matrix.toxenv }}

  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.5"
          - python-version: "3.6"
          - python-version: "3.7"
          - python-version: "3.8"
          - python-version: "3.9"
          - python-version: "3.10"
          - python-version: "pypy3"
        toxenv:
          - "py35"
          - "py36"
          - "py37"
          - "py38"
          - "py39"
          - "py310"
          - "pypy3"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install tox
      - run: tox -e ${{ matrix.toxenv }}

  packaging:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install tox
      - run: tox -e packaging

  macos-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - python-version: "py38"
          - python-version: "py39"
          - python-version: "py310"
        toxenv:
          - "py38"
          - "py39"
          - "py310"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install tox
      - run: tox -e ${{ matrix.toxenv }}

