name: Tests
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  packaging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - run: python -m pip install tox
      - run: tox -e packaging

  pep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - run: python -m pip install tox
      - run: tox -e pep8

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - run: python -m pip install tox
      - run: tox -e black

  run-unit-tests-35:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.5"
      - run: python -m pip install tox
      - run: tox -e py365

  run-unit-tests-36:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - run: python -m pip install tox
      - run: tox -e py36

  run-unit-tests-37:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - run: python -m pip install tox
      - run: tox -e py37

  run-unit-tests-38:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: python -m pip install tox
      - run: tox -e py38

  run-unit-tests-pypy3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "pypy3"
      - run: python -m pip install tox
      - run: tox -e pypy3

  run-unit-tests-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup=python@v2
        with:
          python-version: "py38"
      - run: python -m pip3 install tox
      - run: tox -e py38

  packaging-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - run: python -m pip3 install tox
      - run: tox -e packaging